version: '3'

services:
  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
  
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    environment: 
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_HOST=db

  redis:
    image: redis
    restart: unless-stopped

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example

  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf