version: '3'

services:
  frontend:
    build: 
      context: .
      dockerfile: 1.12_frontend.Dockerfile
    ports:
      - 5000:5000
  
  backend:
    build:
      context: .
      dockerfile: 1.12_backend.Dockerfile
    ports:
      - 8000:8000
    environment: 
      - REDIS=redis
      - DB_USERNAME=postgres
      - DB_PASSWORD=example
      - DB_HOST=db

  redis:
    image: redis
    restart: unless-stopped

  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example